### ISSUE TITLE
The DeepSDF paper

### ISSUE THREAD

**Issue by Rouen007** [marian42/mesh_to_sdf#10]
Hello, when learning the sdf method, i found this awesome method.
i found some questions: 
The DeepSDF paper indicated that the auto decoder method are utilized, but I found no code related to the machine learning method.  Would you mind figuring out the code ?

**Comment by marian42** [comment]
This repository only contains code to calculate SDFs for a given mesh. An example application for this is the data preparation for DeepSDF. This repository contains a method that implements the strategy of sampling points more densly near the surface that was suggested in the DeepSDF paper. If you would like to recreate the data preparation pipeline of the DeepSDF paper, this repository might be useful to you.

You can find the DeepSDF implementation of the authors of DeepSDF [here](https://github.com/facebookresearch/DeepSDF).
I also wrote my own implementation of DeepSDF, which you can find [here](https://github.com/marian42/shapegan). My autodecoder implementation is [here](https://github.com/marian42/shapegan/blob/master/train_sdf_autodecoder.py).

**Comment by Rouen007** [comment]
> This repository only contains code to calculate SDFs for a given mesh. An example application for this is the data preparation for DeepSDF. This repository contains a method that implements the strategy of sampling points more densly near the surface that was suggested in the DeepSDF paper. If you would like to recreate the data preparation pipeline of the DeepSDF paper, this repository might be useful to you.
> 
> You can find the DeepSDF implementation of the authors of DeepSDF [here](https://github.com/facebookresearch/DeepSDF).
> I also wrote my own implementation of DeepSDF, which you can find [here](https://github.com/marian42/shapegan). My autodecoder implementation is [here](https://github.com/marian42/shapegan/blob/master/train_sdf_autodecoder.py).

Thank you very much.
