### ISSUE TITLE
ImportError: The mesh_to_sdf package must be imported before OpenGL is imported.

### ISSUE THREAD

**Issue by DONGTING98** [marian42/mesh_to_sdf#50]
Hello!

I am trying to use **mesh_to_voxels**
`from mesh_to_sdf import mesh_to_voxels`
`import trimesh`
`import pyrender`

`mesh = trimesh.load(file)`
`voxels = mesh_to_voxels(mesh, 64, pad=True)`
`vv, ff, nn, _ = skimage.measure.marching_cubes(vv,level=0)`
`mesh0 = trimesh.Trimesh(vv,ff,nn)`
`mesh0.show()`

and it shows some error
![image](https://github.com/marian42/mesh_to_sdf/assets/110180433/cd5f3dda-0ac9-455b-a555-6d66cc2b1814)
![image](https://github.com/marian42/mesh_to_sdf/assets/110180433/cae0855b-c9b6-486a-8cdc-38d5fcc70184)
what should I do?

Thanks a lot.

**Comment by EricWang12** [comment]
How did you solve this problem?
