### ISSUE TITLE
sample_sdf_near_surface() method samples different number of points 

### ISSUE THREAD

**Issue by tansinjahan** [marian42/mesh_to_sdf#7]
I am trying to sample points near-surface of multiple meshes inside a loop. But it samples different amount of points for different or same mesh running multiple times. I specifically set the number of points 2500 as parameters, i.e. points, **sdf = sample_sdf_near_surface(mesh, number_of_points=2500)**. Is this issue a bug or something happening in my method, I am not sure. Do you have any suggestions?
![Slide1](https://user-images.githubusercontent.com/22454868/82697567-2b313180-9c37-11ea-8d38-3f1e21e9253c.jpg)

**Comment by marian42** [comment]
This is a bug in this project that seems to appear more frequently for smaller numbers of points. I just pushed a fix and I'll update the pypi project in the coming days.
