### ISSUE TITLE
Mesh to SDF transformation fails for thin plate (zero volume) mesh with hole inside it.

### ISSUE THREAD

**Issue by Haetsal-Lee** [marian42/mesh_to_sdf#9]
![image](https://user-images.githubusercontent.com/12162593/83097577-64f4b300-a0e3-11ea-99bf-bb0c1b9dd666.png)
![image](https://user-images.githubusercontent.com/12162593/83097592-6e7e1b00-a0e3-11ea-998d-d60433712314.png)
![image](https://user-images.githubusercontent.com/12162593/83097668-a4230400-a0e3-11ea-926f-6e5d8dac2e9a.png)
![image](https://user-images.githubusercontent.com/12162593/83097791-eba99000-a0e3-11ea-9c12-c931835c3c4f.png)
I tried the codes in README (scan && normal).

I think the transformation from mesh to SDF fails severely. The last image above is recostructed mesh from SDF.

I saw the issue which says zero volume can cause some issues and it was resolved by disabling back-face culling. 

What do you think the reason of problem?
- Is zero volume the problem?
- holes messed sign?

** Update
scan/normal: above last image. (this called bubble effect?)
scan/depth: only positive values are generated.

**Comment by marian42** [comment]
The "sample" method doesn't work with zero volume geometry. The scan based method (with `sign_method="depth"` should work. Having only positive values is expected, as negative values are for points inside the shape and if the shape has zero volume, there are no points inside the shape.

That being said, for a shape with zero volume the SDF and the (unsigned) distance are the same, so I'm not sure why you'd want to generate SDFs for this model.
